### ISSUE TITLE
Adding footer

### ISSUE THREAD

**Issue by YadlaMani** [Omkar-Sonawane-23/Tourism#226] opened 2024-05-15 12:14 UTC
**Is your feature request related to a problem? Please describe.**
The website lacks a footer, which is essential. I would like to add a footer with licensing, copyright, and additional information.

**Describe the solution you'd like**
Adding a good and informative footer

**Additional context**
Add a beautiful footer like this 
![image](https://github.com/Omkar-Sonawane-23/Tourism/assets/133841094/db51aad3-f794-4d36-b96f-3e8c8d2b46ed)

**Comment by YadlaMani** [comment] 2024-05-15 12:15
@Omkar-Sonawane-23 @Disha-Hati @sameer-soni pls assign me this issue under gssoc'24

**Comment by sameer-soni** [comment] 2024-05-15 13:25
@YadlaMani duplicate of #219 .

**Closed by sameer-soni** 2024-05-15 13:25 UTC
